sonar.organization=alovecino-app
sonar.projectKey=alovecino-app
sonar.projectName=AloVecino App
sonar.sourceEncoding=UTF-8

sonar.sources=backend/api-gateway/src/main,backend/auth-service/src/main,backend/usuarios-service/src/main,backend/geo-service/src/main,frontend/src
sonar.tests=backend/api-gateway/src/test,backend/auth-service/src/test,backend/usuarios-service/src/test,backend/geo-service/src/test,frontend/src
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*.test.js
sonar.exclusions=**/target/**,**/node_modules/**,**/coverage/**,**/build/**,frontend/assets/**,**/*.test.js

sonar.java.binaries=backend/api-gateway/target/classes,backend/auth-service/target/classes,backend/usuarios-service/target/classes,backend/geo-service/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/api-gateway/target/site/jacoco/jacoco.xml,backend/auth-service/target/site/jacoco/jacoco.xml,backend/usuarios-service/target/site/jacoco/jacoco.xml,backend/geo-service/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
