BEGIN;

CREATE TABLE IF NOT EXISTS rol (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(60) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS estado_cuenta (
    id_estado_cuenta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    descripcion VARCHAR(255),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS region (
    id_region BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS comuna (
    id_comuna BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    id_region BIGINT NOT NULL REFERENCES region(id_region),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_comuna_region UNIQUE (nombre, id_region)
);

CREATE TABLE IF NOT EXISTS direccion (
    id_direccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle VARCHAR(160) NOT NULL,
    numero VARCHAR(30) NOT NULL,
    codigo_postal VARCHAR(20),
    latitud NUMERIC(10, 7),
    longitud NUMERIC(10, 7),
    id_comuna BIGINT NOT NULL REFERENCES comuna(id_comuna),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_direccion_latitud CHECK (latitud IS NULL OR latitud BETWEEN -90 AND 90),
    CONSTRAINT chk_direccion_longitud CHECK (longitud IS NULL OR longitud BETWEEN -180 AND 180)
);

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut VARCHAR(12) NOT NULL UNIQUE,
    nombre_usuario VARCHAR(120) NOT NULL UNIQUE,
    nombre VARCHAR(160) NOT NULL,
    correo VARCHAR(180) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    id_rol BIGINT NOT NULL REFERENCES rol(id_rol),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS configuracion_usuario (
    id_configuracion_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL UNIQUE REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    notificaciones_push BOOLEAN NOT NULL DEFAULT true,
    notificaciones_email BOOLEAN NOT NULL DEFAULT false,
    recibir_ofertas BOOLEAN NOT NULL DEFAULT true,
    perfil_visible BOOLEAN NOT NULL DEFAULT true,
    radio_ofertas_km NUMERIC(6, 2) NOT NULL DEFAULT 3.00,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_configuracion_radio_ofertas CHECK (radio_ofertas_km >= 0)
);

CREATE TABLE IF NOT EXISTS cliente (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_nacimiento DATE NOT NULL,
    id_usuario BIGINT NOT NULL UNIQUE REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    id_direccion BIGINT NOT NULL REFERENCES direccion(id_direccion),
    id_estado_cuenta BIGINT NOT NULL REFERENCES estado_cuenta(id_estado_cuenta),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS almacen (
    id_almacen BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(140) NOT NULL,
    id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    id_direccion BIGINT NOT NULL REFERENCES direccion(id_direccion),
    id_estado_cuenta BIGINT NOT NULL REFERENCES estado_cuenta(id_estado_cuenta),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_almacen_dueno_nombre_direccion UNIQUE (id_usuario, nombre, id_direccion)
);

CREATE TABLE IF NOT EXISTS sesion_usuario (
    id_sesion_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    dispositivo VARCHAR(120),
    user_agent VARCHAR(500),
    ip_origen VARCHAR(45),
    fecha_login TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_ultimo_uso TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id_refresh_token BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion_usuario BIGINT NOT NULL REFERENCES sesion_usuario(id_sesion_usuario) ON DELETE CASCADE,
    hash_token VARCHAR(128) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    fecha_revocacion TIMESTAMPTZ,
    CONSTRAINT chk_refresh_token_expira_despues CHECK (fecha_expiracion > fecha_creacion)
);

CREATE TABLE IF NOT EXISTS tipo_contacto (
    id_tipo_contacto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS almacen_contacto (
    id_almacen_contacto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_almacen BIGINT NOT NULL REFERENCES almacen(id_almacen) ON DELETE CASCADE,
    id_tipo_contacto BIGINT NOT NULL REFERENCES tipo_contacto(id_tipo_contacto),
    valor VARCHAR(180) NOT NULL,
    nombre_contacto VARCHAR(120),
    es_principal BOOLEAN NOT NULL DEFAULT false,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_almacen_contacto_valor UNIQUE (id_almacen, id_tipo_contacto, valor)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_almacen_contacto_principal
    ON almacen_contacto(id_almacen, id_tipo_contacto)
    WHERE es_principal;

CREATE TABLE IF NOT EXISTS categoria_almacen (
    id_categoria_almacen BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS almacen_categoria (
    id_almacen_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_almacen BIGINT NOT NULL REFERENCES almacen(id_almacen) ON DELETE CASCADE,
    id_categoria_almacen BIGINT NOT NULL REFERENCES categoria_almacen(id_categoria_almacen),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_almacen_categoria UNIQUE (id_almacen, id_categoria_almacen)
);

CREATE TABLE IF NOT EXISTS almacen_horario (
    id_almacen_horario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_almacen BIGINT NOT NULL REFERENCES almacen(id_almacen) ON DELETE CASCADE,
    dia_semana SMALLINT NOT NULL,
    hora_apertura TIME,
    hora_cierre TIME,
    cerrado BOOLEAN NOT NULL DEFAULT false,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_almacen_horario_dia CHECK (dia_semana BETWEEN 1 AND 7),
    CONSTRAINT chk_almacen_horario_horas CHECK (
        cerrado = true OR (hora_apertura IS NOT NULL AND hora_cierre IS NOT NULL AND hora_cierre > hora_apertura)
    ),
    CONSTRAINT uk_almacen_horario_bloque UNIQUE (id_almacen, dia_semana, hora_apertura, hora_cierre)
);

CREATE TABLE IF NOT EXISTS tipo_imagen (
    id_tipo_imagen BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS almacen_imagen (
    id_almacen_imagen BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_almacen BIGINT NOT NULL REFERENCES almacen(id_almacen) ON DELETE CASCADE,
    id_tipo_imagen BIGINT NOT NULL REFERENCES tipo_imagen(id_tipo_imagen),
    url VARCHAR(500) NOT NULL,
    orden INTEGER NOT NULL DEFAULT 0,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_almacen_imagen_orden CHECK (orden >= 0)
);

CREATE TABLE IF NOT EXISTS estado_consulta (
    id_estado_consulta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    descripcion VARCHAR(255),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS consulta (
    id_consulta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES cliente(id_cliente),
    id_almacen BIGINT NOT NULL REFERENCES almacen(id_almacen),
    id_estado_consulta BIGINT NOT NULL REFERENCES estado_consulta(id_estado_consulta),
    respuesta TEXT,
    fecha_respuesta TIMESTAMPTZ,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS consulta_detalle (
    id_consulta_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta BIGINT NOT NULL REFERENCES consulta(id_consulta) ON DELETE CASCADE,
    descripcion TEXT NOT NULL,
    cantidad_solicitada INTEGER NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_consulta_detalle_cantidad CHECK (cantidad_solicitada > 0)
);

CREATE TABLE IF NOT EXISTS valoracion (
    id_valoracion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_estrellas SMALLINT NOT NULL,
    contenido TEXT,
    id_cliente BIGINT NOT NULL REFERENCES cliente(id_cliente),
    id_almacen BIGINT NOT NULL REFERENCES almacen(id_almacen),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_valoracion_cliente_almacen UNIQUE (id_cliente, id_almacen),
    CONSTRAINT chk_valoracion_estrellas CHECK (cantidad_estrellas BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS oferta (
    id_oferta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_almacen BIGINT NOT NULL REFERENCES almacen(id_almacen) ON DELETE CASCADE,
    titulo VARCHAR(140) NOT NULL,
    descripcion TEXT NOT NULL,
    radio_km NUMERIC(6, 2) NOT NULL,
    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_fin TIMESTAMPTZ,
    activa BOOLEAN NOT NULL DEFAULT true,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_oferta_radio CHECK (radio_km > 0),
    CONSTRAINT chk_oferta_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE TABLE IF NOT EXISTS oferta_categoria (
    id_oferta_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_oferta BIGINT NOT NULL REFERENCES oferta(id_oferta) ON DELETE CASCADE,
    id_categoria_almacen BIGINT NOT NULL REFERENCES categoria_almacen(id_categoria_almacen),
    CONSTRAINT uk_oferta_categoria UNIQUE (id_oferta, id_categoria_almacen)
);

CREATE TABLE IF NOT EXISTS cliente_categoria_interes (
    id_cliente_categoria_interes BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES cliente(id_cliente) ON DELETE CASCADE,
    id_categoria_almacen BIGINT NOT NULL REFERENCES categoria_almacen(id_categoria_almacen),
    CONSTRAINT uk_cliente_categoria_interes UNIQUE (id_cliente, id_categoria_almacen)
);

CREATE INDEX IF NOT EXISTS idx_usuario_rol ON usuario(id_rol);
CREATE INDEX IF NOT EXISTS idx_direccion_comuna ON direccion(id_comuna);
CREATE INDEX IF NOT EXISTS idx_direccion_geo_coords ON direccion(latitud, longitud)
    WHERE latitud IS NOT NULL AND longitud IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_almacen_usuario ON almacen(id_usuario);
CREATE INDEX IF NOT EXISTS idx_almacen_direccion ON almacen(id_direccion);
CREATE INDEX IF NOT EXISTS idx_sesion_usuario_usuario ON sesion_usuario(id_usuario);
CREATE INDEX IF NOT EXISTS idx_sesion_usuario_revoked_at ON sesion_usuario(revoked_at);
CREATE INDEX IF NOT EXISTS idx_refresh_token_sesion ON refresh_token(id_sesion_usuario);
CREATE INDEX IF NOT EXISTS idx_refresh_token_fecha_expiracion ON refresh_token(fecha_expiracion);
CREATE INDEX IF NOT EXISTS idx_refresh_token_fecha_revocacion ON refresh_token(fecha_revocacion);
CREATE INDEX IF NOT EXISTS idx_consulta_cliente ON consulta(id_cliente);
CREATE INDEX IF NOT EXISTS idx_consulta_almacen ON consulta(id_almacen);
CREATE INDEX IF NOT EXISTS idx_valoracion_almacen ON valoracion(id_almacen);
CREATE INDEX IF NOT EXISTS idx_oferta_almacen ON oferta(id_almacen);
CREATE INDEX IF NOT EXISTS idx_oferta_vigencia ON oferta(activa, fecha_inicio, fecha_fin);

COMMIT;
