# PostgreSQL Database configuration for QA
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/alovecino_consulta_qa}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# JWT Security configuration for QA
consulta.security.jwt.secret-key=${CONSULTA_JWT_SECRET:mySecretKeyQa}
consulta.security.jwt.expiration-time=86400000

# Logging configuration for QA
logging.level.com.alovecino.consultaservice=INFO